styling index.html
FeliKroder/personal-website pull request #2
Opened 2023-06-27 11:21 UTC by FeliKroder

Hej Nadja, wäre toll wenn du hier einmal drüberschauen würdest.

2023-06-27 20:41 UTC, NadjaKanunnikow requested changes

2023-06-27 20:41 UTC, NadjaKanunnikow commented on index.html
> +      <h1>Feli</h1>
h1 darf es nur 1x geben

2023-06-28 06:15 UTC, gregorsart commented on index.html
> +    <link href="stylesheet.css" rel="stylesheet" />
Die Angabe zum stylesheet also das `<link ... /> ` kommt in der Regel in der Zeile gleich nach dem `<title> ... </title>` und nicht ganz oben.

2023-06-28 06:26 UTC, FeliKroder commented on index.html
> +    <link href="stylesheet.css" rel="stylesheet" />
ah super. Danke! Das wusste ich nicht 😸

2023-06-28 06:38 UTC, FeliKroder commented on index.html
> +      <h1>Feli</h1>
hi Nadja! Gut gesehen! 
War grad auch richtig verwirrt. Warum ich zwei h1 habe. Aber das was du im roten siehst ist das was vorher war, und das grüne ist das, womit ich das rote überschrieben habe.

2023-06-28 06:49 UTC, PeetThesing reviewed
Vielleicht wäre blau schöner?

2023-06-28 06:49 UTC, PeetThesing commented on stylesheet.css
> +  background-color: salmon;
```suggestion
  background-color: skyblue;
```

2023-06-28 06:55 UTC, merged